[pytest]
addopts = -v --alluredir=allure-results
markers =
    smoke: быстрые базовые проверки
    regression: регрессионные тесты
    ui: UI-тесты
    api: API-тесты
log_cli = true
log_cli_level = INFO
